#define DEBOUNCE 40
#define NKRO_DEFAULT_ON true

#define MIDI_ADVANCED

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_CUSTOM_thrrip_1
#define RGB_MATRIX_DEFAULT_HUE 168
#define RGB_MATRIX_DEFAULT_SAT 222
#define RGB_MATRIX_DEFAULT_VAL 185
#define RGB_MATRIX_DEFAULT_SPD 135
